version: '3.7'
volumes:
  pictures:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/masaki/Pictures
services:
  redis:
    image: redis:alpine
    restart: always
  watcher:
    build: .
    image: masarakki/sync-photos
    restart: always
    env_file: .env.production
    command: bundle exec ruby bin/watch
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - pictures:/Pictures
    depends_on:
      - redis
  web:
    build: .
    image: masarakki/sync-photos
    restart: always
    env_file: .env.production
    command: bundle exec rackup -p 9292 -o 0.0.0.0 -E production
    environment:
      - REDIS_URL=redis://redis
    ports:
      - "9292:9292"
    depends_on:
      - redis
  sidekiq:
    build: .
    image: masarakki/sync-photos
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -r ./lib/sync-photos.rb -e production
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - pictures:/Pictures
    depends_on:
      - redis
  upload_raw:
    build: .
    image: masarakki/sync-photos
    env_file: .env.production
    command: bundle exec ruby bin/upload_raw
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - pictures:/Pictures
    depends_on:
      - redis
