version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
  watcher:
    build: .
    image: masarakki/sync-photos
    command: env
    env_file: .env.production
    volumes:
      - "~/Pictures:/Pictures"
    depends_on:
      - redis
