version: '3.7'
volumes:
  pictures:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/masaki/Pictures
services:
  redis:
    image: redis:alpine
    restart: always
  watcher:
    build: .
    image: masarakki/sync-photos
    env_file: .env.production
    command: env
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - pictures:/Pictures
    depends_on:
      - redis
  sidekiq:
    build: .
    image: masarakki/sync-photos
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -q syncphotos -r ./lib/sync-photos.rb -C ./config.yml
    environment:
      - REDIS_URL=redis://redis
    volumes:
       - pictures:/Pictures
    depends_on:
      - redis
